### ISSUE TITLE
[Bug] customization of /var/lib/containers

### ISSUE THREAD

**Issue by daniel-wtd** [fedora-silverblue/issue-tracker#114]
Hi everybody,

during the setup of SB, I wanted to customize my partitions to achieve the following:

- /var/lib/containers on a different subvolume
- /var/lib/libvirt on a different subvolume

Both is not achievable, since the installer will stop with the below error:

```
mount ['--bind', '/mnt/sysimage/var/lib/containers', '/mnt/sysroot/var/lib/containers'] exited with code 32
```

Since the docs state /var/* should be possible, I thought this should be possible.

**Comment by jkonecny12** [comment]
Hi, I'm Anaconda developer. Seems to me that we are getting to some unhealthy recursion mounting or something similar. Unfortunately, installation on RPMOStree is not that simple thing to do because you have basically two installation system roots. Could you please file this to bugzilla.redhat.com on Anaconda component. We can look on this in more detail  on the Anaconda side.

Could you please also attach logs there, thanks!

**Comment by daniel-wtd** [comment]
Hi, thanks for the fast response. Let's start with some logs. I have fetched some and added as them as attachment.

[anaconda.log](https://github.com/fedora-silverblue/issue-tracker/files/5678516/anaconda.log)
[storage.log](https://github.com/fedora-silverblue/issue-tracker/files/5678518/storage.log)
[syslog.log](https://github.com/fedora-silverblue/issue-tracker/files/5678521/syslog.log)
[sysinfo.txt](https://github.com/fedora-silverblue/issue-tracker/files/5678523/sysinfo.txt)

The Bugzilla is opened here: https://bugzilla.redhat.com/show_bug.cgi?id=1906735

**Comment by jkonecny12** [comment]
Let's close this issue and move the conversation to bugzilla. To avoid having two channels.

**Comment by jkonecny12** [comment]
And thanks for creating the bug.
