### ISSUE TITLE
[BUG] Rebuild the .iso to be able to udpate from the GUI

### ISSUE THREAD

**Issue by mcrha** [fedora-silverblue/issue-tracker#181]
Moving this from a downstream bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1981088

Description of problem:
Fedora 34 Silverblue installed from latest iso always returns "Unable to get list of updates: Daemon disappeared" error when checking for updates. It looks like that there is not any way to update clean Fedora 34 Silverblue installation using GUI.

This issue was already fixed in upstream, but gnome-software from the F34 Silverblue iso does not contain this fix. This is a *major* issue and should be fixed in Silverblue - by making a new iso with the fix included.

Sorry for reporting it as a Software issue, but I am not sure where exactly I should report it.

Version-Release number of selected component (if applicable):
gnome-software-40.0-2.fc34.x86_64

How reproducible:
Every time.

Steps to Reproduce:
1. Install Fedora 34 Silverblue from latest available iso.
2. Open GNOME Software and look if there are any available system updates. If not, manually check for updates.
3. Try restarting the computer and trying the previous step multiple times.

Actual results:
Software always shows that there are no new system updates available and checking for them manually returns a "Unable to get list of updates: Daemon disappeared" error.

Additional info:
Upstream ticket: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1224

**Comment by tpopela** [comment]
I don't think that it's possible to respin the already released ISO. For that do so you would have to talk to Fedora Release team. Silverblue it's not any special in this case - you wouldn't probably get the same for Fedora Workstation as well.

**Comment by mcrha** [comment]
It's common to create a new .iso files for download. One of the reasons why the Workstation is named Fedora-Workstation-Live-x86_64-34-1.2.iso (the .2 at the end), or Fedora-Workstation-Live-x86_64-32-1.6.iso (the .6 at the end). I do not know whom does it, thus accessing the spin bug tracker, as suggested on the spin site, felt like a very good candidate.

**Comment by tpopela** [comment]
But these are numbers for the last RC respins that were done before GA. I don't think that what you're proposing is doable (after GA), but I will ask Adam Williamson.

**Comment by AdamWill** [comment]
we do not generally rebuild images officially after GA. it would be up to releng more than QA to do so as some kind of exception. @mohanboddu @nirik wdyt?

**Comment by tpopela** [comment]
I forget put the update here after last Silverblue meeting. - Owen thinks that for Silverblue it shouldn't be a problem as it's not an edition, but a spin so it might have a different rules (and I promised that I will check with releng, so thank you Adam for bringing them here). Also Jirka Eischmann mentioned that for Workstation it would be a problem, because it would mean to retest the new ISO, but as Silverblue is not comprehensively tested at the moment it maybe should be enough if we identify the right compose (and test it) ourselves.

**Comment by AdamWill** [comment]
It doesn't really matter whether it's an "edition" or a "spin", it's not a policy thing, it's more of a process thing - this has been the case since before editions existed, we just don't really do post-release rebuilds of any deliverables, we don't have a process for building them, testing them and shipping them.

In recent years there have been specific cases where we're set up to do regular stable builds - the "cloud" and "container" and "iot" composes under https://kojipkgs.fedoraproject.org/compose/ - and we've had processes for doing some kind of "release" of at least some of those (e.g. publishing the container images to container registries). But outside of that we still don't have anything really in place. It's possible that something could be bodged up on the fly but it requires people to take the time to do the bodging. At least releng and websites people, I guess, and QA people if you want *any* kind of testing of the thing before it gets published at all.

**Comment by cgwalters** [comment]
For what it's worth in Fedora CoreOS we regularly regenerate images and OS updates in a coherent way integrated with CI to form CD.

**Comment by AdamWill** [comment]
sure. it's not really the building part that's an issue, tbh - it's easy enough to do it one-off manually, or set up a new compose to do it regularly (as we have for those three types mentioned above). the bigger issue is how to actually release it. that process is all worked out and written down for the Big Gold Release, but we don't have one for shipping a random one-time respin of one thing some weeks after release.

**Comment by mohanboddu** [comment]
We can run a one off build, and when we had to do it previously, we published them to https://dl.fedoraproject.org/pub/alt/unofficial/releases/

**Comment by juhp** [comment]
Is there any workaround for this, like running `rpm-ostree update`?

**Comment by mcrha** [comment]
> Is there any workaround for this, like running `rpm-ostree update`?

Correct, that's supposed to help. You can use also `flatpak update` to update the Flatpak applications, but once you get a new gnome-software it'll be done by it.

**Comment by AsciiWolf** [comment]
But this is just a workaround, not a solution suitable for end-users, at least in my opinion.

**Comment by AsciiWolf** [comment]
Was the .iso rebuild discussed more further? If so, was it approved? Thanks!

**Comment by tpopela** [comment]
@AsciiWolf no it wasn't.

@mohanboddu but the thing is that won't have it under https://dl.fedoraproject.org/pub/alt/unofficial/releases/ but we want to replace the current official Silverblue 34 ISO (at least I think that's what this issue is about).

**Comment by juhp** [comment]
(Well it might be nice if the regular Live respins also covered Silverblue...
Recently Live images are being refreshed twice a month I think.
Of course Silverblue is not a Live image - though maybe it could be?)

**Comment by tpopela** [comment]
@juhp for the liveCD see - it's tracked in https://teams.fedoraproject.org/project/silverblue/us/88 but it's in the backlog as no-one wasn't working on it.

**Comment by travier** [comment]
Closing as F34 is now EOL
