### ISSUE TITLE
Enable rpm-ostree cliwrap by default

### ISSUE THREAD

**Issue by kuba3351** [fedora-silverblue/issue-tracker#266]
**Is your feature request related to a problem? Please describe.**
Whrn a user tries to run commands such as `dnf` it gets a `command not found` error

**Describe the solution you'd like**
I would like to propose to enable `cliwrap` rpm-ostree feature by default on Silverblue/Kinoite. This is nice and will improve the user experience. For example when user try to run `dnf update` it will be translated to `rpm-ostree update`. When user try to install something using `dnf install` there will be a helpful message that describes the good ways to install something on Silverblue (flatpak, toolbox, package layering). I tested this feature on Fedora Kinoite and ot works very well, and I think it should be considered to enable it by default to improve the user experience.

**Additional context**
I think it could be proposed as a change for Fedora 37

**Comment by hkaancaliskan** [comment]
Instead of translating dnf update to rpm-ostree update, silverblue should show an info like "DNF is the package manager of Fedora. Silverblue is using rpm-ostree as package manager, you should use it." because as we recently saw people copy-paste codes to terminal and accepting everything (Yes I'm looking at you Linus Sebastian), at least user will get the idea of that command found from a website won't work for silverblue.

**Comment by kuba3351** [comment]
Ok, so, cliwrap works like I described, so I think we need to find another way to implement the way you described

**Comment by travier** [comment]
This will be resolved when we complete the transition to bootable containers. This is tracked in https://gitlab.com/fedora/ostree/sig/-/issues/26
