### ISSUE TITLE
Re-build (or prompt to re-build) font cache after installing RPM packaged fonts (overlaying or using GNOME Software)

### ISSUE THREAD

**Issue by NighttimeDriver50000** [fedora-silverblue/issue-tracker#28]
After installing a font through GNOME Software, it prompts to restart, since it installs through `rpm-ostree`, but the font will not be registered until the user manually runs `fc-cache`. This is not a high-priority issue, but I felt it should be documented, and it would be a better user experience to either run `fc-cache` or prompt the user with a dialog saying something like "Update the user font cache?" "The font you installed will not be available until the cache is updated." [Update/Skip]

**Comment by tagoh** [comment]
Yes, this is a known issue, and combining some issues here.

1. When trying to `rpm-ostree install someting-fonts`, a font cache is somehow generated at the user cache directory.   This happens because, although fontconfig has a timestamp in a cache to see if the targeted directories/files are updated, rpm-ostree resets a timestamp after running fc-cache. so fontconfig see the difference of timestamps between in-cache and directories/files and then trying to update caches.   Basically this can be avoided if run fc-cache with SOURCE_DATE_EPOCH envvar. but `SOURCE_DATE_EPOCH=0 rpm-ostree install something-fonts` seems not working. is it because `fc-cache` is called from filetrigger in fontconfig package? dunno.

1. When caches are available at the system directory and the user directory, fontconfig will read the first cache reagardless of its age and the order depends on the config. by default, one in the system directory has a priority.   Basically font caches are supposed to be updated when installing a package though, due to the above two reasons, newly added fonts looks like not available to users.

1. This is potential feature issue and strictly same issue for first one though, we may still see a problem even if we address the above issues.  When users have an user font cache, fontconfig will consider it is the latest cache regardless of the fact, because of the timestamp.

The first one and third one is SB specific issues. the second one is likely to happen on even WS etc. just FYI.

**Comment by tpopela** [comment]
@tagoh made a Silverblue specific quirk in fontconfig - https://bugzilla.redhat.com/show_bug.cgi?id=1823637#c3 that should address this issue, but needs to be tested.

**Comment by tagoh** [comment]
Yes, the updated package is available. that would be appreciated if you can also test it.

**Comment by juhp** [comment]
I think this could be closed now.
