### ISSUE TITLE
[RFE]  replace rpm firefox with flatpak firefox

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#316]
**Is your feature request related to a problem? Please describe.**
fedora silverblue requires restart to update base image programs which leads in many cases to people not updating their system just to avoid reboots , causing users to be stuck on older insecure versions of the web browser , so having firefox update independently from the system will be very nice to have

**Describe the solution you'd like**
i think the best solution is removing firefox from the base image and replacing it with the flatpak build , for migration it will be good to make the flatpak version use the same profile files as the rpm or add a first run script to the flatpak to move the profile files over to the ~/.var directory where the flatpak version will put them normally

**Comment by starship-boi** [comment]
I agree. In my opinion, every app that can be a Flatpak should be a Flatpak because it increases system stability, allows users to easily remove programs if they want to, and makes sure that the user always has up to date apps. Having Firefox on the base image does not seem smart because most people have strong opinions on which browser they use, and therefore many people would want to use something else and remove Firefox. However, for less technical users, it would be hard to see that removing it was even an option. In addition, web browsers are applications that need security updates very keenly because they are the gateway by which most security threats attack computers. As allaeddineomc said, many people will not update their base image very often, so having a Flatpak version of Firefox instead of RPM would reduce the impact of zero-days for those people.

**Comment by travier** [comment]
Duplicate of https://github.com/fedora-silverblue/issue-tracker/issues/288
