### ISSUE TITLE
Software Center not loading anything

### ISSUE THREAD

**Issue by vordenken** [fedora-silverblue/issue-tracker#327]
**Describe the bug**
After opening the software center nothing loads - no app names, no thumbnails etc.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Open software center
2. -

**Expected behavior**
There should be apps listed not just empty thumbnails

**Screenshots**
![Screenshot 2022-08-18 at 13 57 01](https://user-images.githubusercontent.com/62395860/185389187-bc65decd-bca8-4263-ac86-a3a41f862710.png)

**OS version:**
```
Version: 36.20220818.0
```

**Additional context**
-

**Comment by har7an** [comment]
Hit the same issue on F37 silverblue. When I navigate to the "Updates" tab I also see this:

![Screenshot from 2022-09-24 08-58-56](https://user-images.githubusercontent.com/99636919/192084883-66664401-456d-43a1-8d87-e66496628a32.png)

**Comment by mcrha** [comment]
I cannot tell whether the 'Permission denied' is the same thing as the original report, that might be seen on the gnome-software's terminal, which can be started as these two commands: `gnome-software --quit` (to close the current session, if it won't work, then "kill -9 `pidof gnome-software`") followed by simple `gnome-software`.

The problem with the 'Permission denied' is that the libdnf cache version is outdated and needs rebuilding, but the gnome-software process doesn't have access to the necessary directory/files, because it's not running as a privileged user. It's filled upstream as [1] and it also references [2].

[1] https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1793
[2] https://github.com/fedora-silverblue/issue-tracker/issues/257

**Comment by sanecito** [comment]
The [1793 issue noted by mcrha](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1793) has been patched. However, it will be in GNOME 44, not any 43.x releases according to contributors in that issue.

So in order for this issue to be patched in 43.x to make general day to day updates and upgrades possible to 44 or whatever version is out when 43.x is EOL via gnome-software the Silverblue maintainers will need to pull in what looks like a total of three patches going by the 1793 comments:

- https://github.com/coreos/rpm-ostree/pull/4097
- https://github.com/coreos/rpm-ostree/pull/4099
- https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1531

**Comment by hozza** [comment]
I get this same issue, a broken Software Center as shown in the OP. 

This happened immediately after installing/layering a Local Package (Dropbox rpm in this case) on Silverblue. I also notice @sanecito has a local package of proton vpn - perhaps this local package related.

**Comment by hozza** [comment]
OS version:

```
Deployments:
● fedora:fedora/37/x86_64/silverblue
                  Version: 37.20230406.0 (2023-04-06T00:43:29Z)
               BaseCommit: ae60887a4bc16a185e680c0de7c9f8c3d6d2172abaf544cf8c945efcb00ebb1a
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
          LayeredPackages: cascadia-code-fonts distrobox kmod-nvidia langpacks-en_GB xorg-x11-drv-nvidia
            LocalPackages: nautilus-dropbox-2022.12.05-1.fc37.x86_64
```

Running `killall gnome-software` then `gnome-software --verbose` showed errors: 

```
19:57:17:172 Gs  failed to get updates: failed to obtain lock 'metadata': Failed to create file “/var/run/dnf-metadata.lock.19S521”: Permission denied
```

I fixed this by running `rpm-ostree refresh-md` then `killall gnome-software` then `gnome-software --verbose` again, no errors.

Now Software Center / gnome-software works as expected.
