### ISSUE TITLE
Bug: Fedora32 gnome-software tries to use dnf

### ISSUE THREAD

**Issue by daniel-wtd** [fedora-silverblue/issue-tracker#36]
I recently tested f32 silverblue (rebase from 31) and it seems gnome-software is trying to use dnf instead of rpm-ostree. rpm-ostree itself is working fine.

**Comment by tpopela** [comment]
Can you please be more specific? What GNOME Software version? In what operations it's trying to use dnf? Can you describe the exact steps? How did you noticed it's using dnf? Is there any error being shown in the UI or printed to logs?

**Comment by daniel-wtd** [comment]
no problem:

I am on:

- Fedora 32.20200328.n.0
- gnome-software 3.36.0

When opening gnome-software and checking for updates, you will see the message in the screenshot. In addition, no rpm-ostree updates are shown, flatpak updates are shown.
![Screenshot from 2020-03-30 20-25-42](https://user-images.githubusercontent.com/6490538/77947816-c5729a00-72c4-11ea-853f-9ad7f5390149.png)

**Comment by kalev** [comment]
OK, I spent some time debugging this and it turns out to be fallout from enabling the fedora-cisco-openh264 repo by default. libdnf doesn't handle repo_gpgcheck=1 enabled repos correctly and tries to download the repo keys when it shouldn't.

We already have a Fedora 32 blocker bug for a closely related issue, https://bugzilla.redhat.com/show_bug.cgi?id=1768206 and it seems to be progressing along nicely. It looks like fedora-cisco-openh264 is going to be switched over to mirrormanager; that should automatically fix this issue here as well.

**Comment by daniel-wtd** [comment]
Afaik, Firefox will support h264 out of the box with Firefox75 + it will support flatpak. Therefore, is the cisco-h264 repo needed by default?

**Comment by tpopela** [comment]
> Afaik, Firefox will support h264 out of the box with Firefox75 + it will support flatpak. Therefore, is the cisco-h264 repo needed by default?

But that's the official (Mozilla) Firefox flatpak. This is intended for the Firefox RPM that's part of the base image (or together with the Firefox Fedora Flatpak if we figure how to use it (if needed))

**Comment by daniel-wtd** [comment]
Thanks for the explanation :)
