### ISSUE TITLE
Change build and release cadence

### ISSUE THREAD

**Issue by travier** [fedora-silverblue/issue-tracker#384]
We're currently building and releasing a new version of Silverblue every day and shipping that directly to users, before we even run OpenQA tests on it.

The proposal is to change this to a "every other week" release cadence to let time to test things before they are released to all users.

We would also keep a ref/stream/branch that behaves just like what we have right now (daily builds immediately released) for users that want faster updates and for general testing. This would also let us do update tests from latest release to latest stable.

This would be similar in spirit to what Fedora CoreOS does.

**Comment by travier** [comment]
This heavily depend on https://github.com/fedora-silverblue/issue-tracker/issues/334 & https://github.com/fedora-silverblue/issue-tracker/issues/359 to make this manageable.

**Comment by tpopela** [comment]
We were thinking about this 3 years ago as well, but it's something where we need some buy-in from the Fedora QA as well. There were many opened questions around critical CVEs, urgent bug fixes and how it all fits together. But we're definitely interested in this - basically similar to what Workstation is doing through Software - https://pagure.io/fedora-workstation/issue/107.

**Comment by gjask** [comment]
Are less frequent releases requirement for some kind of build testing? Because this is one of features I quite like about Silverblue. You can have setup automatic staged updates and stop caring. Whenever you restart your system, you always get latest fedora. Which seems simple, elegant and beautiful.

Now imagine if there was need to care which updates can wait to next release and which should trigger build immediately.

**Comment by travier** [comment]
I'll close this issue in favor of the one in the Fedora Atomic Desktop issue tracker: https://gitlab.com/fedora/ostree/sig/-/issues/2

While they are not strictly the same issue, this is one likely to happen as part of that change.
