### ISSUE TITLE
add support for heic images

### ISSUE THREAD

**Issue by ikke-t** [fedora-silverblue/issue-tracker#505]
**Is your feature request related to a problem? Please describe.**

The modern phones use .HEIC image files instead of .JPG. While I try seeing them via (Nextcloud->) Firefox, I don't get the images drawn on SilverBlue 39.

**Describe the solution you'd like**
The proper heif/heic libraries would be in base image.

**Describe alternatives you've considered**
I have layered the following,  I believe this worked in F38:
```
          LayeredPackages: ffmpeg-free heif-pixbuf-loader intel-media-driver langpacks-en
                           libavcodec-freeworld libheif-freeworld libheif-tools
                           nextcloud-client rpmfusion-free-release
                           rpmfusion-nonfree-release tmux wireguard-tools zsh
```

**Additional context**
Images -screen from Nextcloud. JPG images are shown, but heic not.
![image](https://github.com/fedora-silverblue/issue-tracker/assets/1146409/efd360e5-0a0b-46a0-8558-5d04fabd1cc6)

**Comment by chrisawi** [comment]
This isn't possible because `libheif-freeworld` is an RPM Fusion package. `libheif` in Fedora only supports AVIF, which is already covered by `libavif` and `avif-pixbuf-loader` in the base image.

Firefox [doesn't support HEIF](https://bugzilla.mozilla.org/show_bug.cgi?id=1402293) but `qt-heif-image-plugin` might be useful for nextcloud-client.  If you need further assistance, please feel free to ask in https://discussion.fedoraproject.org

**Comment by travier** [comment]
Reverse linking to discussion: https://discussion.fedoraproject.org/t/fedora-silverblue-39-heic-problem/101299

**Comment by mcatanzaro** [comment]
Surely this should be closed? HEIC will not be allowed in Fedora for the foreseeable future.

**Comment by superuser-miguel** [comment]
@mcatanzaro Why do you say that? There are request for it, and the software is GPL/MIT license so why not?

**Comment by travier** [comment]
As far as I understand, we already ship libheif, and that's as far as we can go to. Support for more patent encumbered formats can not be added to Fedora for legal reasons. You will have to look for those in RPM Fusion.

**Comment by mcatanzaro** [comment]
[We'd need $65 million annual budget to cover just the two patent pools that post rates on Wikipedia.](https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding#Patent_license_terms) And we'd need to pay all the patent pools. If you are a billionaire, then let's talk, but otherwise no.

We are not going to do this illegally by not paying the rightsholders. That's not an option.

**Comment by mcatanzaro** [comment]
(And since we don't precisely track Fedora installs, we have to pay a maximum royalty, not a per-seat royalty.)
