### ISSUE TITLE
bad experience with default totem/video player

### ISSUE THREAD

**Issue by dikasetyaprayogi** [fedora-silverblue/issue-tracker#518]
**Describe the bug**
not sure if this happen to everyone but based on my experience both in f38 and f39 silverblue fresh install, the default totem shipped always broke (cant play, black screen, sounds only, failed video thumbnail, etc..)

**To Reproduce**
open videos with default totem from file manager (fresh installed OS)

**Expected behavior**
a default shipped software should be stable and just works

**Screenshots**
![Screenshot from 2023-12-14 07-26-40](https://github.com/fedora-silverblue/issue-tracker/assets/33314785/a4e558b6-970d-494b-8d54-aed9ed102abb)

**OS version:**
```
fedora:fedora/39/x86_64/silverblue
                  Version: 39.20231205.0 (2023-12-05T00:55:28Z)
               BaseCommit: ae1afb462f69a9170bdfa24ef9fc3059b2366480c4fbcfac2a15c0fc65487d8a
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
          LayeredPackages: eog-plugins unar
```

**Additional context**
advanced user may know their way to resolve this issue, in my experience either by installing totem,openh264 or ffmpegthumbnailer via rpm-ostree. but i wish silverblue just work out of the box to be more appeal for general user.

**Comment by chrisawi** [comment]
Fedora is limited by US law. Probably the best improvement that could be made is to have a Fedora flatpak version of the openh264 extension, which appears to be on the roadmap: https://gitlab.com/fedora/sigs/flatpak/fedora-flatpaks/-/issues/13#h264-video-playback-out-of-the-box

Ideally, thumbnailers should be flatpaks as well: https://github.com/flatpak/flatpak/issues/4923

Currently, the best option for most users is to install apps from Flathub rather than layering with rpm-ostree.

**Comment by dikasetyaprayogi** [comment]
thanks for the pointers, might be useful information for new people getting their hands into fedora
