### ISSUE TITLE
Use ptyxis (formerly Prompt) as the default terminal

### ISSUE THREAD

**Issue by travier** [fedora-silverblue/issue-tracker#520]
**Is your feature request related to a problem? Please describe.**

> Prompt is a terminal for GNOME with first-class support for containers.
>
> Flatpak is the intended and preferred distribution mechanism.

See:
- https://blogs.gnome.org/chergert/2023/12/14/prompt/
- https://gitlab.gnome.org/chergert/ptyxis (https://gitlab.gnome.org/chergert/prompt)

**Describe the solution you'd like**

Replace the default terminal application with Prompt, or at least include it by default.

**Describe alternatives you've considered**

N/A

**Additional context**

Suggested for Workstation:
* https://pagure.io/fedora-workstation/issue/261#comment-888447
* https://pagure.io/fedora-workstation/issue/417

If Fedora Workstation does not want to include it, we can consider including it on top of the default terminal in Silverblue.

**Comment by chrisawi** [comment]
I'm a big fan of Prompt already, but I don't think it should be shipped along with gnome-terminal. Having two similar terminals in the menu would be unpolished. If Silverblue doesn't want to diverge from Workstation here, this should go on hold until they make a decision (which may mean waiting for GNOME, apparently).

From the quoted text, I presume you intend to ship it as a flatpak. That seems reasonable, however, I think there should still be *something* in the base image in case flatpak is broken somehow (rolling back wouldn't help if the problem is in `/var`). I immediately thought of `weston-terminal` as an ultra-basic fallback. It's currently part of the `weston` package, but I guess it could be split out. It's also officially [only a demo](https://gitlab.freedesktop.org/wayland/weston/-/issues/566) but would be better than nothing, and as long as it continues not to ship a .desktop file, it wouldn't be exposed in the UI, only usable via Alt+F2.

**Comment by travier** [comment]
From my perspective, there must be a terminal app available at all times from the base image.

So for me there are only two options:
- We replace the current one (unlikely given the accessibility issues mentioned in the ticket linked)
- We add Prompt, either as a Flatpak or in the image

**Comment by almereyda** [comment]
Prompt has been renamed to [chergert/ptyxis](https://gitlab.gnome.org/chergert/ptyxis).

**Comment by travier** [comment]
Looks like the accessibility issues are being sorted out: https://blogs.gnome.org/chergert/2024/02/29/accessibility-in-ptyxis/

Testing welcomed!

**Comment by A6GibKm** [comment]
Imho Silverblue should just follow what workstation does in this regard.

**Comment by chergert** [comment]
The necessary VTE patches are available in Fedora 40 now (including a11y patches). Presumably Ptyxis package will land shortly.

**Comment by travier** [comment]
This is happening for Fedora 41: https://pagure.io/fedora-workstation/issue/417
