### ISSUE TITLE
libxml2 package conflict

### ISSUE THREAD

**Issue by 1player** [fedora-silverblue/issue-tracker#574]
```
error: Could not depsolve transaction; 1 problem detected:
 Problem: package virt-manager-common-4.1.0-5.fc40.noarch from fedora requires python3-libxml2, but none of the providers can be installed
  - package python3-libxml2-2.12.8-1.fc40.x86_64 from updates requires libxml2(x86-64) = 2.12.8-1.fc40, but none of the providers can be installed
  - package python3-libxml2-2.12.5-1.fc40.x86_64 from fedora requires libxml2(x86-64) = 2.12.5-1.fc40, but none of the providers can be installed
  - package python3-libxml2-2.12.6-1.fc40.x86_64 from updates-archive requires libxml2(x86-64) = 2.12.6-1.fc40, but none of the providers can be installed
  - cannot install both libxml2-2.12.8-1.fc40.x86_64 from updates and libxml2-2.12.7-1.fc40.x86_64 from @System
  - cannot install both libxml2-2.12.5-1.fc40.x86_64 from fedora and libxml2-2.12.7-1.fc40.x86_64 from @System
  - cannot install both libxml2-2.12.6-1.fc40.x86_64 from updates-archive and libxml2-2.12.7-1.fc40.x86_64 from @System
  - package virt-manager-4.1.0-5.fc40.noarch from fedora requires virt-manager-common = 4.1.0-5.fc40, but none of the providers can be installed
  - conflicting requests
```

Layered packages: `ddccontrol docker docker-compose dunst firefoxpwa langpacks-en_GB libvirt liquidctl pavucontrol
                           printer-driver-brlaser python3-pyudev restic steam-devices vim-default-editor virt-manager zsh`

**Comment by miabbott** [comment]
These problems are usually not an issue that can be solved by the Atomic Desktop team. This might be a packaging issue or more often, this is a problem with the DNF mirror not being up to date or just connection issues talking to the mirror.

Check `sudo journalctl -b -u rpm-ostreed` (or all of the journal) to see if there is any evidence of connectivity problems.

If this problem is repeatable, you may want to head to the the [Fedora Discussion Forum](https://discussion.fedoraproject.org/) for more help.

FWIW, I tried `rpm-ostree install virt-manager` on simple Fedora 40 Silverblue host (40.20240618.0) and was successful.
