### ISSUE TITLE
Tree based installations require at least 6GB of RAM

### ISSUE THREAD

**Issue by felipeborges** [fedora-silverblue/issue-tracker#64]
This issues was initially [raised for virtual machines](https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/141), but can affect users in bare metal too.

Silverblue needs to load its image in the memory for the installation to proceed.

I wonder if we could shrink the memory requirement somehow with ostree.

Thoughts?

**Comment by jkonecny12** [comment]
Hello,

AFAICT the reason here is the stage2 image. The stage2 image is squashfs image which contain all the pieces required to start the installation (including Anaconda). Standard way of creating DVD.ISO is to create stage2 (minimal image), initrd, vmlinuz and pack these together to DVD.ISO. If you have repositories for offline installations then these should be put to DVD.ISO (not stage2). This is how for example Fedora Server DVD works.

SilverBlue is doing this differently for some (not known) reasons to me. SilverBlue contains stage2 image which also contains flatpak repository and ostree image for the installation. That means, that if you downloading stage2 image from the net you have to have RAM to download whole stage2 + ostree image + flatpak repository and then to start the installation.

The amount of RAM depends on how you boot the installation. If you use DVDRom then the stage2 image is mounted from the DVD and you don't have to download everything to RAM. Depends on how stage2 mount works (not sure about that). The similar use-case works for NFS. However, for http/https/ftp you have to download whole stage2 to the RAM to start the installation.

To solve this issue, I think the SilverBlue should move ostree image and flatpak repository to DVD.iso (layer above) for offline installations and for http installation we should modify Anaconda to use Fedora OSTree repository if DVD.ISO is not available. I suggest the same for build-in Flatpaks.

**Comment by owtaylor** [comment]
> SilverBlue is doing this differently for some (not known) reasons to me. SilverBlue contains stage2 image which also contains flatpak repository and ostree image for the installation. 

Well the reason for the Flatpak repository location is that you proposed it be put there to match the location of the ostree repository (https://bugzilla.redhat.com/show_bug.cgi?id=1734970#c1) - but for the ostree repository, I'm not sure the background - @cgwalters and @dustymabe might remember. 

So as I understand what would be needed:

 - pungi would need to be modified to have ostree and flatpak embedding logic instead of delegating the "heavy lifting" to the lorax templates
- anaconda needs to be changed to look for the flatpak and system repositories in DVD.iso (or a configurable other location)

There's nothing there that is *hard* but considering the setup and cycle times for working on pungi image creation, it's probably a couple of weeks of work for the pungi side - not sure about the Anaconda side.

There's also a good-and-bad side effect from switching to network sources for a network install - without extra work you'd get the latest Silverblue version and Flatpaks rather than the version when the ISO was created. Avoids an extra pointless update step, but there's less validation than on the release candidate, so there's some small chance you'd end up with a broken Fedora and not be able to roll back to a working Fedora.

**Comment by jkonecny12** [comment]
> Well the reason for the Flatpak repository location is that you proposed it be put there to match the location of the ostree repository (https://bugzilla.redhat.com/show_bug.cgi?id=1734970#c1) - but for the ostree repository, I'm not sure the background - @cgwalters and @dustymabe might remember.

True, the flatpaks just mimics the same behavior as ostree to make it simpler for implementation in Anaconda and also for the existing lorax solution. Thanks for pointing here the bug and refreshing my memory ;).


> So as I understand what would be needed:
> 
>     * pungi would need to be modified to have ostree and flatpak embedding logic instead of delegating the "heavy lifting" to the lorax templates
> 
>     * anaconda needs to be changed to look for the flatpak and system repositories in DVD.iso (or a configurable other location)

Good point. We have to add new kernel cmdline option for flatpaks repository position. That could be only for mounting local source if there won't be enough time and then extended. Then we have to mount the repository somewhere. These changes should be doable in a reasonable time.

**Comment by travier** [comment]
Is this still the case? I've done several installations with 4GB of RAM only and they went fine.

**Comment by travier** [comment]
I'm going to close this one for now as I've made new installations with 4GB that went fine. If we want to support less than that we can re-open this one.
