### ISSUE TITLE
Sudoers should be required to enter password to install packages with rpm-ostree install

### ISSUE THREAD

**Issue by yilkalargaw** [fedora-silverblue/issue-tracker#66]
I am loving my fedora silverblue but it bothers me that sudoers are not asked for a password when the install layered packages with ```rpm-ostree install```. In mainstream fedora-workstation systems a sudoer always has to enter a password to install packages with dnf. This is a security measure which is taken to reduce sudoers from compromising the main root user.

I think the same can be achieved by modifying the permission and ownership of the rpm-ostree binary and modifying the default sudoers file.

**Comment by HarryMichal** [comment]
I second this idea. When I started to use Silverblue, it instantly felt a bit weird being able to install (resp. layer) packages system-wide without typing a password.

**Comment by jlebon** [comment]
The way this is implemented is in https://src.fedoraproject.org/rpms/fedora-release/blob/master/f/org.projectatomic.rpmostree1.rules. This was done so that GNOME Software doesn't spam users for prompts whenever it needs to check or stage updates. IIRC this is on parity with its behaviour on traditional Workstation. I think you should be able to override it by adding an earlier polkit rule in `/etc` which just always denies those actions.

(Worth highlighting the `subject.local == true` bit, which means this only works on local connections, such as via VGA or serial. So e.g. you still need to use `sudo` or go through PolicyKit to update when SSH'ing into the machine.)

**Comment by HarryMichal** [comment]
Thank you for the exaplanation @jlebon! I'm still not sure which approach is the correct one, though. The current behaviour is certainly better from the usability point of view but I'm not sure about the security one. But I'm no expert so I leave that decision to somebody else.

> IIRC this is on parity with its behaviour on traditional Workstation.

I don't think Workstation behaves the same.

**Comment by yilkalargaw** [comment]
Thanks for the suggestion. I managed to fix it for my case.

The requirement to ask sudores for ```sudo``` to perform updates installs and uninstalls was a security measure incase the sudoer forgot to lock a session. I think it is necessary to ensure that the default security assumptions work as expected on both workstation and silverblue more than ensuring that a specific software behaves the same way on them.  In a multi-user setup the admin expects that sudoers are asked for password for software installation more than gnome-softaware-center behaving as it used to.

Also since gnome software center is used in gnome only it is going to be tricky when silverblue spins arise (i.e. something like [kinoite rebases](https://discussion.fedoraproject.org/t/kinoite-a-kde-and-now-xfce-version-of-fedora-silverblue/147).

**Comment by yilkalargaw** [comment]
Also gnome-software-center still keeps spamming me with password request for updates. I had to switch to a different desktop environment to keep my sanity.
\

**Comment by TheOneandOnlyJakfrost** [comment]
I have been using SB since before this issue tracker site was setup and I have not had Gnome SW spamming me with unnecessary popups for, well ever. I am the only user of this system, and am a sudoer as part of the wheel group with admin rights. Possibly, if your user is setup as non-admin, this is why your are getting those popups, which would then relate to issue #55. As I said though, I am the only user on this system, others here may be sharing their PC.

**Comment by yilkalargaw** [comment]
@TheOneandOnlyJakfrost You might be right. I have a separate root,sudoer and users. Either way I no longer have to deal with the issue of Gnome SW. 

I think my argument still holds though I still think ```It is necessary to ensure that the default security assumptions work as expected on both workstation and silverblue more than ensuring that a specific software behaves the same way on them. ```

I'll leave the issue open in-case it might need more discussion. I have solved the issue for my specific case so feel free to close it. Thank you very much for the assist.
